services:
  GreyLiteratureClassifier:
    image: greylitdockerimagedebug
    container_name: GreyLitContainerDebug
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    volumes:
      - type: bind
        source: .
        target: /GreyLiteratureClassifier
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    stdin_open: true
    tty: true
    command: "/bin/bash"
